//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.SampleWcfRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://samplewcf.dev.com/", ConfigurationName="SampleWcfRef.IWcfService")]
    public interface IWcfService {
        
        // CODEGEN: Generating message contract since element name GetRamdomGuidResult from namespace https://samplewcf.dev.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://samplewcf.dev.com/IWcfService/GetRamdomGuid", ReplyAction="https://samplewcf.dev.com/IWcfService/GetRamdomGuidResponse")]
        WcfClient.SampleWcfRef.GetRamdomGuidResponse GetRamdomGuid(WcfClient.SampleWcfRef.GetRamdomGuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://samplewcf.dev.com/IWcfService/GetRamdomGuid", ReplyAction="https://samplewcf.dev.com/IWcfService/GetRamdomGuidResponse")]
        System.Threading.Tasks.Task<WcfClient.SampleWcfRef.GetRamdomGuidResponse> GetRamdomGuidAsync(WcfClient.SampleWcfRef.GetRamdomGuidRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRamdomGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRamdomGuid", Namespace="https://samplewcf.dev.com/", Order=0)]
        public WcfClient.SampleWcfRef.GetRamdomGuidRequestBody Body;
        
        public GetRamdomGuidRequest() {
        }
        
        public GetRamdomGuidRequest(WcfClient.SampleWcfRef.GetRamdomGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRamdomGuidRequestBody {
        
        public GetRamdomGuidRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRamdomGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRamdomGuidResponse", Namespace="https://samplewcf.dev.com/", Order=0)]
        public WcfClient.SampleWcfRef.GetRamdomGuidResponseBody Body;
        
        public GetRamdomGuidResponse() {
        }
        
        public GetRamdomGuidResponse(WcfClient.SampleWcfRef.GetRamdomGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://samplewcf.dev.com/")]
    public partial class GetRamdomGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRamdomGuidResult;
        
        public GetRamdomGuidResponseBody() {
        }
        
        public GetRamdomGuidResponseBody(string GetRamdomGuidResult) {
            this.GetRamdomGuidResult = GetRamdomGuidResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : WcfClient.SampleWcfRef.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<WcfClient.SampleWcfRef.IWcfService>, WcfClient.SampleWcfRef.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfClient.SampleWcfRef.GetRamdomGuidResponse WcfClient.SampleWcfRef.IWcfService.GetRamdomGuid(WcfClient.SampleWcfRef.GetRamdomGuidRequest request) {
            return base.Channel.GetRamdomGuid(request);
        }
        
        public string GetRamdomGuid() {
            WcfClient.SampleWcfRef.GetRamdomGuidRequest inValue = new WcfClient.SampleWcfRef.GetRamdomGuidRequest();
            inValue.Body = new WcfClient.SampleWcfRef.GetRamdomGuidRequestBody();
            WcfClient.SampleWcfRef.GetRamdomGuidResponse retVal = ((WcfClient.SampleWcfRef.IWcfService)(this)).GetRamdomGuid(inValue);
            return retVal.Body.GetRamdomGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfClient.SampleWcfRef.GetRamdomGuidResponse> WcfClient.SampleWcfRef.IWcfService.GetRamdomGuidAsync(WcfClient.SampleWcfRef.GetRamdomGuidRequest request) {
            return base.Channel.GetRamdomGuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfClient.SampleWcfRef.GetRamdomGuidResponse> GetRamdomGuidAsync() {
            WcfClient.SampleWcfRef.GetRamdomGuidRequest inValue = new WcfClient.SampleWcfRef.GetRamdomGuidRequest();
            inValue.Body = new WcfClient.SampleWcfRef.GetRamdomGuidRequestBody();
            return ((WcfClient.SampleWcfRef.IWcfService)(this)).GetRamdomGuidAsync(inValue);
        }
    }
}
